# Generated by Django 3.1.6 on 2021-02-12 14:59

import blog.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن وارد کنید', regex='0[1-9][0-9]{9}')], verbose_name='شماره تلفن')),
                ('position', models.CharField(blank=True, choices=[('normal', 'ساده'), ('writer', 'نویسنده'), ('editor', 'ویراستار'), ('manager', 'مدیر')], default='normal', max_length=8, verbose_name='رده کاربر')),
                ('image', models.ImageField(blank=True, upload_to=blog.models.profile_user_path, verbose_name='تصویر پروفایل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'وبلاگ نویس',
                'verbose_name_plural': 'وبلاگ نویسان',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='دسته\u200cبندی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='زیر مجموعه')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('is_accepted', models.BooleanField(choices=[(False, 'تایید نمی\u200cکنم'), (True, 'تایید می\u200cکنم')], default=False, verbose_name='تایید کردن')),
                ('is_activated', models.BooleanField(choices=[(False, 'غیرفعال'), (True, 'فعال')], default=False, verbose_name='وضعیت فعالیت')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('like_qty', models.IntegerField(default=0, verbose_name='تعداد پسندیدن')),
                ('dislike_qty', models.IntegerField(default=0, verbose_name='تعداد نپسندیدن')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.post_user_path, verbose_name='تصویر پست')),
                ('category', models.ForeignKey(on_delete=models.SET(blog.models.get_patent), to='blog.category', verbose_name='دسته\u200cبندی')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('is_accepted', models.BooleanField(choices=[(False, 'تایید نمی\u200cکنم'), (True, 'تایید می\u200cکنم')], default=False, verbose_name='تایید کردن')),
                ('is_activated', models.BooleanField(choices=[(False, 'غیرفعال'), (True, 'فعال')], default=False, verbose_name='وضعیت فعالیت')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('like_qty', models.IntegerField(default=0, verbose_name='تعداد پسندیدن')),
                ('dislike_qty', models.IntegerField(default=0, verbose_name='تعداد نپسندیدن')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(0, 'null'), (1, 'like'), (-1, 'dislike')], default=0, verbose_name='مقدار')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='وبلاگ نویس')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک\u200cها',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
