# Generated by Django 3.1.5 on 2021-01-27 20:21

import blog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=80, verbose_name='نام')),
                ('last_name', models.CharField(max_length=80, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='ایمیل')),
                ('username', models.CharField(max_length=80, unique=True, verbose_name='نام کاربری')),
                ('password', models.TextField(verbose_name='رمز ورود')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل وارد کنید', regex='09[0-9]{9}')])),
                ('image', models.ImageField(upload_to='profile/', verbose_name='تصویر پروفایل')),
                ('position', models.CharField(choices=[('normal', 'ساده'), ('writer', 'نویسنده'), ('editor', 'ویراستار'), ('manager', 'مدیر')], default='normal', max_length=8, verbose_name='رده کاربر')),
            ],
            options={
                'verbose_name': 'وبلاگ نویس',
                'verbose_name_plural': 'وبلاگ نویسان',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('category', models.CharField(max_length=80, verbose_name='دسته\u200cبندی')),
                ('category_full', models.TextField(verbose_name='دسته\u200cبندی - نام کامل')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('image', models.ImageField(null=True, upload_to=blog.models.user_directory_path, verbose_name='تصویر پست')),
                ('like_qty', models.IntegerField(default=0, verbose_name='تعداد پسندیدن')),
                ('dislike_qty', models.IntegerField(default=0, verbose_name='تعداد نپسندیدن')),
                ('creator_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.bloguser')),
                ('parent_post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tag', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'تگ-پست',
                'verbose_name_plural': 'تگ-پست\u200cها',
                'unique_together': {('tag', 'post')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(through='blog.TagPost', to='blog.Tag'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[('null', 0), ('like', 1), ('dislike', -1)], default='null', verbose_name='مقدار')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloguser', verbose_name='وبلاگ نویس')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک\u200cها',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
