# Generated by Django 3.1.5 on 2021-01-27 21:47

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ویرایش')),
                ('old_text', models.TextField(verbose_name='متن')),
                ('old_category', models.CharField(blank=True, max_length=80, verbose_name='دسته\u200cبندی')),
                ('old_category_full', models.TextField(blank=True, verbose_name='دسته\u200cبندی - نام کامل')),
                ('old_image', models.ImageField(null=True, upload_to=blog.models.user_directory_path, verbose_name='تصویر پست')),
                ('editor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.bloguser', verbose_name='وبلاگ نویس')),
            ],
            options={
                'verbose_name': 'ویرایش',
                'verbose_name_plural': 'ویرایش\u200cها',
            },
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_time',
            new_name='create_datetime',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.bloguser', verbose_name='وبلاگ نویس'),
        ),
        migrations.CreateModel(
            name='TagEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.edit', verbose_name='ویرایش')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tag', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'تگ-ویرایش',
                'verbose_name_plural': 'تگ-ویرایش\u200cها',
                'unique_together': {('tag', 'edit')},
            },
        ),
        migrations.AddField(
            model_name='edit',
            name='old_tag',
            field=models.ManyToManyField(blank=True, through='blog.TagEdit', to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='edit',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست'),
        ),
    ]
