# Generated by Django 3.1.6 on 2021-02-05 22:43

import blog.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent_post',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=80, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.profile_user_path, verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن وارد کنید', regex='0[0-9]{10}')], verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='position',
            field=models.CharField(blank=True, choices=[('normal', 'ساده'), ('writer', 'نویسنده'), ('editor', 'ویراستار'), ('manager', 'مدیر')], default='normal', max_length=8, verbose_name='رده کاربر'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
                ('like_qty', models.IntegerField(default=0, verbose_name='تعداد پسندیدن')),
                ('dislike_qty', models.IntegerField(default=0, verbose_name='تعداد نپسندیدن')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
            },
        ),
    ]
