# Generated by Django 3.1.6 on 2021-02-18 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210217_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(0, 'null'), (1, 'like'), (-1, 'dislike')], default=0, verbose_name='مقدار')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment', verbose_name='کامنت\u200cلایک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='وبلاگ نویس')),
            ],
            options={
                'verbose_name': 'کامنت\u200cلایک',
                'verbose_name_plural': 'کامنت\u200cلایک\u200cها',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(0, 'null'), (1, 'like'), (-1, 'dislike')], default=0, verbose_name='مقدار')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست\u200cلایک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='وبلاگ نویس')),
            ],
            options={
                'verbose_name': 'پست\u200cلایک',
                'verbose_name_plural': 'پست\u200cلایک\u200cها',
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
