# Generated by Django 3.1.6 on 2021-02-07 13:20

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210207_1532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagedit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tagedit',
            name='edit',
        ),
        migrations.RemoveField(
            model_name='tagedit',
            name='tag',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_accepted',
            field=models.BooleanField(choices=[(False, 'تایید نمی\u200cکنم'), (True, 'تایید می\u200cکنم')], default=False, verbose_name='تایید کردن'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_activated',
            field=models.BooleanField(choices=[(False, 'غیرفعال'), (True, 'فعال')], default=False, verbose_name='وضعیت فعالیت'),
        ),
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.IntegerField(choices=[(0, 'null'), (1, 'like'), (-1, 'dislike')], default=0, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.post_user_path, verbose_name='تصویر پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_accepted',
            field=models.BooleanField(choices=[(False, 'تایید نمی\u200cکنم'), (True, 'تایید می\u200cکنم')], default=False, verbose_name='تایید کردن'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_activated',
            field=models.BooleanField(choices=[(False, 'غیرفعال'), (True, 'فعال')], default=False, verbose_name='وضعیت فعالیت'),
        ),
        migrations.DeleteModel(
            name='Edit',
        ),
        migrations.DeleteModel(
            name='TagEdit',
        ),
    ]
