# Generated by Django 3.1.6 on 2021-02-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210221_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='comment',
            new_name='instance',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='post',
            new_name='instance',
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'instance')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'instance')},
        ),
    ]
