# Generated by Django 3.1.6 on 2021-02-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210221_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment', verbose_name='کامنت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست'),
        ),
    ]
