# Generated by Django 3.1.6 on 2021-02-26 08:00

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210225_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.SET(blog.models.get_patent), to='blog.category', verbose_name='دسته\u200cبندی'),
        ),
    ]
