# Generated by Django 3.1.6 on 2021-02-26 08:03

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210226_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=models.SET(blog.models.get_patent), to='blog.category', verbose_name='دسته\u200cبندی'),
            preserve_default=False,
        ),
    ]
